### ISSUE TITLE
Inconsistent prefixes

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-kfe-rix-motion#20]
Makefile defines "PLC:KFE:RIX:MOTION"
pragmas define "PLC:RIX:MOTION"

Need to be consistent for use in new pmps-ui update

**Comment by klauer** [comment]
I'm going to be making some updates here for AT2K2, and we may as well add in these changes.

Easiest path would be to change the `Makefile`-defined prefix. That seems to be the opposite of what we might want, though?

**Comment by klauer** [comment]
Ah, that makes a lot more sense. I've apparently already forgotten our naming standard.
